info:
  contact: {}
paths:
  /word/{word}:
    get:
      consumes:
      - application/json
      description: ask if a word is valid
      parameters:
      - description: the word is valid
        in: path
        name: word
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: word
      summary: word
      tags:
      - example
swagger: "2.0"
