name: Run tests

on:
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm ci, build and test
        run: |
          cd hangoff-app
          npm ci
          npm run build --if-present
          npm test
